u1 = User.create(email: 'ferris@ferryrules.com', username: 'ferryrules', password_digest: 'asd', permission: 'Super Admin', fname: 'Ferris', lname: 'Boran')
u2 = User.create(email: 'ali.reubenstone@flatironschool.com', username: 'alirules', password_digest: 'asd', permission: 'Super Admin', fname: 'Ali', lname: 'Reubenstone')

c1 = Company.create(name: "FerryRules")
c2 = Company.create(name: "ABC Solutions, LLC")
c3 = Company.create(name: "PackingPal")

cu1 = CompUser.create(company: c1, user: u1)
cu2 = CompUser.create(company: c2, user: u1)
cu3 = CompUser.create(company: c3, user: u2)

e1 = Employee.create(full_name: "Sam Perrey", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Married', w4_allowance: 0, active_status: 'Terminated', company: c1)
e2 = Employee.create(full_name: "Amy Velligan", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, active_status: 'Terminated', company: c1)
e3 = Employee.create(full_name: "Tracy Hsu", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Married', w4_allowance: 0, active_status: 'Terminated', company: c1)
e4 = Employee.create(full_name: "Rayanne Buchianico", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, active_status: 'Terminated', company: c1)
e5 = Employee.create(full_name: "Danielle Jasper", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'CTO - Chief Technology Officer')
e6 = Employee.create(full_name: "Dan Fyfe", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'CITO - Chief Information Technology Officer')
e7 = Employee.create(full_name: "Ferris Boran", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'CEO - Chief Executive Officer')
e8 = Employee.create(full_name: "Troy Gooden", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'CLO - Chief Learning Officer')
e9 = Employee.create(full_name: "William Sinn", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'CCO - Chief Compliance Officer')
e10 = Employee.create(full_name: "Jacob Lam", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'CIO - Chief Information Officer')
e11 = Employee.create(full_name: "Jeffrey Marks", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'CXO - Chief Experience Officer')
e12 = Employee.create(full_name: "David Bernier", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'CFO - Chief Financial Officer')
e13 = Employee.create(full_name: "Edgar Ong", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'COO - Chief Operating Officer')
e14 = Employee.create(full_name: "Elaina Shi", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'CSO - Chief Sustainability Officer')
e15 = Employee.create(full_name: "Kevin Malazarte", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'CSO - Chief Security Officer')
e16 = Employee.create(full_name: "Robert O'Gara", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'CIO - Chief Investment Officer')
e17 = Employee.create(full_name: "Sarah Granoff", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'CPO - Chief Procurement Officer')
e18 = Employee.create(full_name: "Soyeong Oh", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'CBO - Chief Branding Officer')
e19 = Employee.create(full_name: "Tommy Lau", pay_type: "Salary", pay_rate: 250000.00, filing_status: 'Single', w4_allowance: 0, company: c1, title: 'CDO - Chief Data Officer')

# d1 = Department.create(name: "Finance", company: c1)
# d2 = Department.create(name: "Admin", company: c1)
# d3 = Department.create(name: "IT", company: c1)
# d4 = Department.create(name: "Engineer", company: c1)
# d5 = Department.create(name: "Marketing", company: c1)
# d6 = Department.create(name: "Recruiting", company: c1)
# d7 = Department.create(name: "Product", company: c1)

t1 = Ticket.create(title: 'Computer Crashed', description: "Hit it was golf club and now it doesn't work", priority: 'High', category: 'Hardware', department: d3, company: c1, user: u1, ticket_status: 'Open')
t2 = Ticket.create(title: 'Software Needed', description: "Need software to steal money", priority: 'High', category: 'Software', department: d4, company: c1, user: u2, ticket_status: 'Open')
t3 = Ticket.create(title: 'Cat Ate Mouse', description: "Need a new one", priority: 'Medium', category: 'Hardware', department: d3, company: c1, user: u1, ticket_status: 'Open')
t4 = Ticket.create(title: 'Google Not Working', description: "Keeps telling me to try again", priority: 'Low', category: 'Software', department: d4, company: c1, user: u1, ticket_status: 'Open')
t5 = Ticket.create(title: 'Screen is black!', description: "My computer screen is black. I can't see anything. Please fix ASAP!", priority: 'High', category: 'Hardware', department: d3, company: c1, user: u1, ticket_status: 'Pending')
t6 = Ticket.create(title: 'Adobe Needed', description: "Need adobe to photoshop myself at this epic yacht party I missed", priority: 'High', category: 'Software', department: , company: c1, user: u2, ticket_status: 'Closed')
t7 = Ticket.create(title: 'Where is my muffin?', description: "I had it in the fridge and now it's gone. :(", priority: 'Medium', category: 'Food', department: , company: c1, user: u1, ticket_status: 'Closed')
t8 = Ticket.create(title: 'Permanent marker is out of ink', description: "Can I borrow yours? I need to color in this 10' x 10' poster board completely black", priority: 'Medium', category: 'Favor', department: , company: c1, user: u1, ticket_status: 'Pending')

pr1 = Payroll.create(start_date: 'June 1, 2019', end_date: 'June 8, 2019', check_date: 'June 11, 2019', company: c1)
pr2 = Payroll.create(start_date: 'June 9, 2019', end_date: 'June 16, 2019', check_date: 'June 19, 2019', company: c1)

pc1 = Paycheck.create(hours: 40, payroll: pr1, employee: e5)
pc2 = Paycheck.create(hours: 40, payroll: pr1, employee: e6)
pc3 = Paycheck.create(hours: 40, payroll: pr1, employee: e7)
pc4 = Paycheck.create(hours: 40, payroll: pr1, employee: e8)
pc5 = Paycheck.create(hours: 40, payroll: pr1, employee: e9)
pc6 = Paycheck.create(hours: 40, payroll: pr1, employee: e10)
pc7 = Paycheck.create(hours: 40, payroll: pr1, employee: e11)
pc8 = Paycheck.create(hours: 40, payroll: pr1, employee: e12)
pc9 = Paycheck.create(hours: 40, payroll: pr1, employee: e13)
pc10 = Paycheck.create(hours: 40, payroll: pr1, employee: e14)
pc11 = Paycheck.create(hours: 40, payroll: pr1, employee: e15)
pc12 = Paycheck.create(hours: 40, payroll: pr1, employee: e16)
pc13 = Paycheck.create(hours: 40, payroll: pr1, employee: e17)
pc14 = Paycheck.create(hours: 40, payroll: pr1, employee: e18)
pc15 = Paycheck.create(hours: 40, payroll: pr1, employee: e19)

pc21 = Paycheck.create(hours: 35, payroll: pr2, employee: e5)
pc22 = Paycheck.create(hours: 35, payroll: pr2, employee: e6)
pc23 = Paycheck.create(hours: 35, payroll: pr2, employee: e7)
pc24 = Paycheck.create(hours: 35, payroll: pr2, employee: e8)
pc25 = Paycheck.create(hours: 35, payroll: pr2, employee: e9)
pc26 = Paycheck.create(hours: 35, payroll: pr2, employee: e10)
pc27 = Paycheck.create(hours: 35, payroll: pr2, employee: e11)
pc28 = Paycheck.create(hours: 35, payroll: pr2, employee: e12)
pc29 = Paycheck.create(hours: 35, payroll: pr2, employee: e13)
pc210 = Paycheck.create(hours: 35, payroll: pr2, employee: e14)
pc211 = Paycheck.create(hours: 35, payroll: pr2, employee: e15)
pc212 = Paycheck.create(hours: 35, payroll: pr2, employee: e16)
pc213 = Paycheck.create(hours: 35, payroll: pr2, employee: e17)
pc214 = Paycheck.create(hours: 35, payroll: pr2, employee: e18)
pc215 = Paycheck.create(hours: 35, payroll: pr2, employee: e19)

#
# pa1 = PaycheckAdjustment.create(adj_type: 'Addition', adj_amount: 456.78, description: 'Additional Cool Person Bonus', paycheck: pc1, employee: e1)
#
ra1 = RecurringAdjustment.create(adj_type: 'Addition', adj_amount: 12345.67, description: 'Awesome Person Bonus', employee: e1)
